version: "3.8"

services:
  flask-app:
    build:
      context: .
    container_name: flask-app
    ports:
      - "8888:8888"
    depends_on:
      - mongo
    volumes:
      - .:/app
    environment:
      - MONGO_URI=mongodb://mongo:27017/

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
